python3 -m Preprocess.unzip
echo 'unzip done'
python3 -m Preprocess.meta
echo 'process metafile'
python3 -m Preprocess.preprocess
echo 'preprocess done'
python3 -m Preprocess.anony
echo 'anonymize files'
python3 -m Preprocess.integrate
echo 'integrate done'
python3 -m Preprocess.make_bout
echo 'bouts done'